# lightning.pytorch==2.0.6
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      log_model: true
      experiment_name: ${oc.env:ZAP_ENV_NAME}
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        save_top_k: 1
        mode: min
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        min_delta: 0.001
        patience: 5
        verbose: true
        strict: true
    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 1e-2
        device: null # will be infered automatically but "None" is required because "cpu" is the default
    - class_path: lightning.pytorch.callbacks.RichModelSummary
  max_epochs: 200
