# lightning.pytorch==2.0.6
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: demo
      log_model: true
      tags:
        example_tag_1: 123
        example_tag_2: 789
  callbacks:
    class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      monitor: val_loss
      save_top_k: 1
      mode: min
  max_epochs: 10
  max_time: null
model:
  class_path: zap.models.MyResnetModel
  init_args:
    num_classes: 12
    bias: true
data:
  class_path: zap.data_modules.CustomDataModule
  init_args:
    data_dir: data
    transforms:
      - class_path: torchvision.transforms.ToTensor
      - class_path: torchvision.transforms.Resize
        init_args:
          size:
            - 32
            - 32
          antialias: true
    train_split: 0.7
    test_split: 0.2
    val_split: 0.1
    batch_size: 64
    num_workers: 0
    pin_memory: true
    shuffle: true
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false
    foreach: null
    maximize: false
    capturable: false
    differentiable: false
    fused: null
