# lightning.pytorch==2.0.6
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: demo
      log_model: true
      tags:
        example_tag_1: 123
        example_tag_2: 789
  callbacks:
    class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      monitor: val_loss
      save_top_k: 1
      mode: min
  max_epochs: 20
  max_time: null
  log_every_n_steps: 2
model:
  class_path: zap.segmentation.models.UNet
  init_args:
    encoder_name: efficientnet-b2
    encoder_depth: 5
    encoder_weights: imagenet
    activation: sigmoid
    num_classes: 1
    loss_fn:
      class_path: torch.nn.BCEWithLogitsLoss
data:
  class_path: zap.segmentation.data_modules.SegmentationDataModule
  init_args:
    data_dir: data/segmentation
    transforms:
      - class_path: torchvision.transforms.ToTensor
      - class_path: torchvision.transforms.Resize
        init_args:
          size:
            - 1024
            - 1024
          antialias: true
    train_split: 0.6
    test_split: 0
    val_split: 0.4
    batch_size: 3
    num_workers: 0
    pin_memory: true
    shuffle: true
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false
    foreach: null
    maximize: false
    capturable: false
    differentiable: false
    fused: null
